Repository HyperGAN/HyperGAN, pull requests merged in 2020-08, with the labels that each got.

#268 Better default configuration
  bin/hypergan
  hypergan/cli.py
  hypergan/configuration.py
  hypergan/configurations/colorizer.json
  hypergan/configurations/default.json
Labels: enhancement

#267 [feature] colorizer super resolution example
  examples/colorizer.py
  hypergan/configurations/colorizer-super-resolution.json
Labels: enhancement, experiment

#271 Differential augmentation
  hypergan/configurable_component.py
  hypergan/configurations/aligned.json
  hypergan/configurations/differential_augmentation.json
  hypergan/configurations/simpler-generator.json
  hypergan/gan_component.py
  hypergan/gans/ali_gan.py
  hypergan/gans/aligned_gan.py
  hypergan/gans/aligned_interpolate_gan.py
  hypergan/gans/base_gan.py
  hypergan/gans/standard_gan.py
  hypergan/layer.py
  hypergan/layers/multi_head_attention.py
  hypergan/samplers/aligned_sampler.py
  hypergan/samplers/factorization_batch_walk_sampler.py
  hypergan/train_hook_collection.py
  hypergan/train_hooks/base_train_hook.py
  hypergan/train_hooks/differential_augmentation_train_hook.py
Labels: enhancement, experiment

#277 Electron UI
  bin/hypergan
  hypergan/cli.py
  hypergan/samplers/base_sampler.py
  hypergan/samplers/batch_walk_sampler.py
  hypergan/samplers/factorization_batch_walk_sampler.py
  hypergan/samplers/needs_pytorch/style_walk_sampler.py
  hypergan/samplers/y_sampler.py
  hypergan/server/websocket_server.py
  hypergan/threaded_tk_viewer.py
  hypergan/train_hooks/initialize_as_autoencoder.py
  hypergan/train_hooks/match_support_train_hook.py
  hypergan/viewer.py
  requirements.txt
  ui/main.js
  ui/package-lock.json
  ui/package.json
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/logo192.png
  ui/public/logo512.png
  ui/public/manifest.json
  ui/public/robots.txt
  ui/src/App.css
  ui/src/App.js
  ui/src/App.test.js
  ui/src/api/Connection.js
  ui/src/api/HgApiClient.js
  ui/src/index.css
  ui/src/index.js
  ui/src/logo.svg
  ui/src/setupTests.js
Labels: enhancement, high priority

#265 Component level model parallel and initial multi device architecture
  bin/hypergan
  hypergan/backends/backend.py
  hypergan/backends/multi_gpu_backend.py
  hypergan/backends/single_gpu_backend.py
  hypergan/backends/tpu_backend.py
  hypergan/configurable_component.py
  hypergan/gan_component.py
  hypergan/gans/base_gan.py
  hypergan/gans/standard_gan.py
  hypergan/samplers/aligned_sampler.py
  hypergan/trainers/base_trainer.py
Labels: enhancement, high priority

#282 CPU backend
  hypergan/backends/cpu_backend.py
  hypergan/gans/base_gan.py
  hypergan/trainable_gan.py
Labels: enhancement
